In [69]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-flower-dataset/IRIS.csv


In [70]:
import numpy as np 
import pandas as pd

In [71]:
df = pd.read_csv("/kaggle/input/iris-flower-dataset/IRIS.csv")

In [72]:
print(df.head())
print(df.shape)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
(150, 5)


In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [74]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [75]:
df['species'] = df['species'].replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})

In [76]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1

In [77]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

In [78]:
from sklearn.model_selection import train_test_split as tts

In [79]:
x_train,x_test,y_train,y_test = tts(X,Y,test_size = 0.2, random_state=42)

In [80]:
# print(x_train)
# print(y_test)

# model building

In [81]:
from sklearn.neighbors import KNeighborsClassifier


In [82]:
knn_clf = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
knn_clf.fit(x_train,y_train)

KNeighborsClassifier()

In [87]:
# x_test = x_test.reshape(-1,1)
y_pred = knn_clf.predict(x_test)

In [88]:
# y_pred = knn_clf.predict(x_test)

In [89]:
# x_test

In [90]:
pd.DataFrame({'Actual':y_test,'predicted':y_pred})

Actual  predicted
0        2          2
1        1          1
2        3          3
3        2          2
4        2          2
5        1          1
6        2          2
7        3          3
8        2          2
9        2          2
10       3          3
11       1          1
12       1          1
13       1          1
14       1          1
15       2          2
16       3          3
17       2          2
18       2          2
19       3          3
20       1          1
21       3          3
22       1          1
23       3          3
24       3          3
25       3          3
26       3          3
27       3          3
28       1          1
29       1          1

In [91]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [92]:
score = accuracy_score(y_test, y_pred)
print(score)

1.0


In [93]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9
           3       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [94]:
mat = confusion_matrix(y_test, y_pred)
print(mat)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
